name: virtual_closet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  geolocator: ^9.0.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  image_picker: ^1.1.2
  palette_generator: ^0.3.3+7
  provider: ^6.1.5
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
