// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtQWPWpBnCY8NfRausAK2XlhsvVg4iwqg',
    appId: '1:860878388510:web:275c00d9befeb3f040dd0f',
    messagingSenderId: '860878388510',
    projectId: 'learning-firebase-bddb1',
    authDomain: 'learning-firebase-bddb1.firebaseapp.com',
    storageBucket: 'learning-firebase-bddb1.appspot.com', // <-- FIXED
    measurementId: 'G-BTFPSL6HTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJqiCLP_H3rcUHSTySCCAsX0qP1m2qeA',
    appId: '1:860878388510:android:8383171cd26f66b940dd0f',
    messagingSenderId: '860878388510',
    projectId: 'learning-firebase-bddb1',
    storageBucket: 'learning-firebase-bddb1.appspot.com', // <-- FIXED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhoZr7AdnwubrVqwLibX4fTh-s5mmL5c',
    appId: '1:860878388510:ios:5995eb668593676340dd0f',
    messagingSenderId: '860878388510',
    projectId: 'learning-firebase-bddb1',
    storageBucket: 'learning-firebase-bddb1.appspot.com', // <-- FIXED
    iosBundleId: 'com.example.virtualCloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVhoZr7AdnwubrVqwLibX4fTh-s5mmL5c',
    appId: '1:860878388510:ios:5995eb668593676340dd0f',
    messagingSenderId: '860878388510',
    projectId: 'learning-firebase-bddb1',
    storageBucket: 'learning-firebase-bddb1.appspot.com', // <-- FIXED
    iosBundleId: 'com.example.virtualCloset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtQWPWpBnCY8NfRausAK2XlhsvVg4iwqg',
    appId: '1:860878388510:web:599d587203d53aa240dd0f',
    messagingSenderId: '860878388510',
    projectId: 'learning-firebase-bddb1',
    authDomain: 'learning-firebase-bddb1.firebaseapp.com',
    storageBucket: 'learning-firebase-bddb1.appspot.com', // <-- FIXED
    measurementId: 'G-SYJSPM0TMZ',
  );
}
